import React, { useState } from 'react';
import { Database, Key, Check, Copy, AlertCircle, Shield, Sparkles } from 'lucide-react';
import { isSupabaseConfigured, supabaseConfigWarning } from '../../lib/supabase';

interface PengaturanViewProps {
  darkMode?: boolean;
}

export const PengaturanView: React.FC<PengaturanViewProps> = ({ darkMode = false }) => {
  const [copiedSql, setCopiedSql] = useState(false);

  const supabaseSqlSchema = `-- 1. Buat tabel articles di SQL Editor Supabase:
CREATE TABLE IF NOT EXISTS public.articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  slug TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'bahtsul-masail',
  category_label TEXT DEFAULT 'Bahtsul Masail',
  author TEXT DEFAULT 'LBM At-Taroqqy Sarang',
  date TEXT,
  hijri_date TEXT,
  read_time TEXT DEFAULT '5 mnt baca',
  thumbnail TEXT,
  summary TEXT,
  content TEXT,
  arabic_text TEXT,
  arabic_source TEXT,
  arabic_translation TEXT,
  tags TEXT[] DEFAULT ARRAY['Pesantren', 'Sarang', 'Turats'],
  views INT DEFAULT 0,
  status TEXT DEFAULT 'published'
);

-- 2. Aktifkan Row Level Security (RLS) & Kebijakan Akses:
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

-- Publik dapat membaca artikel:
CREATE POLICY "Public read articles" ON public.articles
  FOR SELECT USING (true);

-- User autentikasi / admin dapat mengelola artikel:
CREATE POLICY "Admin write articles" ON public.articles
  FOR ALL USING (auth.role() = 'authenticated');
`;

  const handleCopySql = () => {
    navigator.clipboard.writeText(supabaseSqlSchema);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 2500);
  };

  return (
    <div className="space-y-6 max-w-4xl">
      <div>
        <h2 className="text-xl sm:text-2xl font-bold font-serif-heading">
          Pengaturan Database Supabase
        </h2>
        <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
          Integrasi database PostgreSQL & Otentikasi Supabase untuk Portal Admin Pesantren At-Taroqqy Sarang.
        </p>
      </div>

      {/* Status Card */}
      <div className={`p-6 rounded-2xl border shadow-xs ${
        darkMode ? 'bg-[#062417] border-emerald-900/60' : 'bg-white border-slate-200'
      }`}>
        <div className="flex items-center justify-between pb-4 border-b border-slate-200 dark:border-emerald-900/60">
          <div className="flex items-center gap-3">
            <div className={`w-10 h-10 rounded-xl flex items-center justify-center ${
              isSupabaseConfigured
                ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300'
                : 'bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300'
            }`}>
              <Database className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-sm">Status Koneksi Supabase</h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Client SDK: <code className="text-[11px] font-mono">@supabase/supabase-js</code>
              </p>
            </div>
          </div>

          <span className={`px-3 py-1 rounded-full text-xs font-bold ${
            isSupabaseConfigured
              ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300 border border-emerald-300 dark:border-emerald-800'
              : 'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300 border border-amber-300 dark:border-amber-800'
          }`}>
            {isSupabaseConfigured ? 'Terhubung (Active)' : 'Placeholder (Siap Dikonfigurasi)'}
          </span>
        </div>

        {/* Diagnostic Warning */}
        {supabaseConfigWarning && (
          <div className="mt-4 p-3.5 rounded-xl bg-amber-50 dark:bg-amber-950/50 text-amber-800 dark:text-amber-300 border border-amber-300 dark:border-amber-800 flex items-start gap-2.5 text-xs">
            <AlertCircle className="w-5 h-5 text-amber-600 dark:text-amber-400 shrink-0 mt-0.5" />
            <div>
              <p className="font-bold">Peringatan Konfigurasi Lingkungan:</p>
              <p className="mt-0.5 leading-relaxed">{supabaseConfigWarning}</p>
              <p className="mt-1 text-[11px] opacity-90">
                Pastikan nilai <code>VITE_SUPABASE_URL</code> adalah URL HTTPS (contoh: <code>https://your-project.supabase.co</code>) dari dashboard Supabase &gt; Project Settings &gt; API.
              </p>
            </div>
          </div>
        )}

        {/* Instructions */}
        <div className="mt-5 space-y-4 text-xs">
          <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
            Untuk mengaktifkan sinkronisasi langsung ke project Supabase Anda, tambahkan variabel lingkungan berikut ke file <code className="px-1.5 py-0.5 rounded-sm bg-slate-100 dark:bg-emerald-950 font-mono text-[11px]">.env</code>:
          </p>

          <div className="p-4 rounded-xl bg-slate-900 text-emerald-300 font-mono text-xs space-y-1 overflow-x-auto">
            <p>VITE_SUPABASE_URL="https://xxxxxxxx.supabase.co"</p>
            <p>VITE_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6..."</p>
          </div>

          <div className="flex items-start gap-2 p-3 rounded-xl bg-blue-50 dark:bg-blue-950/40 text-blue-800 dark:text-blue-300 border border-blue-200 dark:border-blue-900">
            <Sparkles className="w-4 h-4 shrink-0 mt-0.5" />
            <p className="text-[11px] leading-relaxed">
              Saat variabel tersebut belum diisi, CMS tetap dapat digunakan sepenuhnya secara interaktif dengan sistem local state dan mock data turats.
            </p>
          </div>
        </div>
      </div>

      {/* SQL Table Creation Helper */}
      <div className={`p-6 rounded-2xl border shadow-xs ${
        darkMode ? 'bg-[#062417] border-emerald-900/60' : 'bg-white border-slate-200'
      }`}>
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <Key className="w-4 h-4 text-[#C9A227]" />
            <h3 className="font-serif-heading font-bold text-base">
              Skrip SQL Tabel Artikel (Supabase SQL Editor)
            </h3>
          </div>
          <button
            type="button"
            onClick={handleCopySql}
            className="px-3 py-1.5 rounded-xl border border-slate-300 dark:border-emerald-900/80 hover:bg-slate-100 dark:hover:bg-emerald-950/60 text-xs font-semibold flex items-center gap-1.5 transition cursor-pointer"
          >
            {copiedSql ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copiedSql ? 'Tersalin!' : 'Salin Skrip SQL'}</span>
          </button>
        </div>

        <p className="text-xs text-slate-500 dark:text-slate-400 mb-3">
          Salin dan jalankan skrip SQL ini di menu <strong>SQL Editor</strong> dashboard Supabase Anda untuk membuat tabel dan aturan RLS:
        </p>

        <div className="relative">
          <pre className="p-4 rounded-xl bg-slate-900 text-slate-200 font-mono text-[11px] overflow-x-auto leading-relaxed max-h-72 border border-slate-800">
            {supabaseSqlSchema}
          </pre>
        </div>
      </div>
    </div>
  );
};
